package jadis.element.accessflags;

public enum AccessFlag {
	PUBLIC, PRIVATE, PROTECTED, STATIC, FINAL, VOLATILE, TRANSIENT, SYNTHETIC, ENUM, SUPER, INTERFACE, ABSTRACT, ANNOTATION, SYNCHRONIZED, BRIDGE, VARARGS, NATIVE, STRICT;
}
